add manual check to all jobs

diff --git a/.github/workflows/pipeline-bucket1-census-datasets-prod.yml b/.github/workflows/pipeline-bucket1-census-datasets-prod.yml
--- a/.github/workflows/pipeline-bucket1-census-datasets-prod.yml
+++ b/.github/workflows/pipeline-bucket1-census-datasets-prod.yml
@@ -24,6 +24,20 @@ jobs:
       - name: Start containers
         run: docker-compose -f cit-api/docker-compose.yml up --build cit-api-pipeline
 
+        # docker-compose will return 0 even if python container returns non-zero or crashes
+        # ensure job fails if python container returns non-zero code or crashes
+      - name: check Container Status
+        run: | 
+          container_status=$(docker ps --filter 'status=exited' --format '{{.Status}}')
+          if [[ $container_status == *"Exited (0)"* ]]; 
+          then 
+            echo "Container exited successfully"
+          else 
+            echo "Container exited with error: $container_status"
+            exit 1
+          fi
+        
+
   run-census-subdivisions-2016:
     runs-on: ubuntu-latest
     steps:
@@ -42,7 +56,20 @@ jobs:
 
       - name: Start containers
         run: docker-compose -f cit-api/docker-compose.yml up --build cit-api-pipeline
-  
+
+        # docker-compose will return 0 even if python container returns non-zero or crashes
+        # ensure job fails if python container returns non-zero code or crashes
+      - name: check Container Status
+        run: | 
+          container_status=$(docker ps --filter 'status=exited' --format '{{.Status}}')
+          if [[ $container_status == *"Exited (0)"* ]]; 
+          then 
+            echo "Container exited successfully"
+          else 
+            echo "Container exited with error: $container_status"
+            exit 1
+          fi
+
   run-census-subdivisions:
     runs-on: ubuntu-latest
     steps:
@@ -61,3 +88,16 @@ jobs:
 
       - name: Start containers
         run: docker-compose -f cit-api/docker-compose.yml up --build cit-api-pipeline
+
+        # docker-compose will return 0 even if python container returns non-zero or crashes
+        # ensure job fails if python container returns non-zero code or crashes
+      - name: check Container Status
+        run: | 
+          container_status=$(docker ps --filter 'status=exited' --format '{{.Status}}')
+          if [[ $container_status == *"Exited (0)"* ]]; 
+          then 
+            echo "Container exited successfully"
+          else 
+            echo "Container exited with error: $container_status"
+            exit 1
+          fi        
diff --git a/.github/workflows/pipeline-bucket2-SA-datasets-prod.yml b/.github/workflows/pipeline-bucket2-SA-datasets-prod.yml
--- a/.github/workflows/pipeline-bucket2-SA-datasets-prod.yml
+++ b/.github/workflows/pipeline-bucket2-SA-datasets-prod.yml
@@ -27,6 +27,20 @@ jobs:
 
       - name: Start containers
         run: docker-compose -f cit-api/docker-compose.yml up --build cit-api-pipeline
+        
+        # docker-compose will return 0 even if python container returns non-zero or crashes
+        # ensure job fails if python container returns non-zero code or crashes
+      - name: check Container Status
+        run: | 
+          container_status=$(docker ps --filter 'status=exited' --format '{{.Status}}')
+          if [[ $container_status == *"Exited (0)"* ]]; 
+          then 
+            echo "Container exited successfully"
+          else 
+            echo "Container exited with error: $container_status"
+            exit 1
+          fi                
+          
 
   run-small-business-count-by-csd:
     runs-on: ubuntu-latest
@@ -46,7 +60,20 @@ jobs:
 
       - name: Start containers
         run: docker-compose -f cit-api/docker-compose.yml up --build cit-api-pipeline
-
+        
+        # docker-compose will return 0 even if python container returns non-zero or crashes
+        # ensure job fails if python container returns non-zero code or crashes
+      - name: check Container Status
+        run: | 
+          container_status=$(docker ps --filter 'status=exited' --format '{{.Status}}')
+          if [[ $container_status == *"Exited (0)"* ]]; 
+          then 
+            echo "Container exited successfully"
+          else 
+            echo "Container exited with error: $container_status"
+            exit 1
+          fi                
+          
   run-core-housing-need-by-csd:
     runs-on: ubuntu-latest
     steps:
@@ -65,7 +92,20 @@ jobs:
 
       - name: Start containers
         run: docker-compose -f cit-api/docker-compose.yml up --build cit-api-pipeline
-            
+        
+        # docker-compose will return 0 even if python container returns non-zero or crashes
+        # ensure job fails if python container returns non-zero code or crashes
+      - name: check Container Status
+        run: | 
+          container_status=$(docker ps --filter 'status=exited' --format '{{.Status}}')
+          if [[ $container_status == *"Exited (0)"* ]]; 
+          then 
+            echo "Container exited successfully"
+          else 
+            echo "Container exited with error: $container_status"
+            exit 1
+          fi                
+                      
   run-businesses-by-csd:
     runs-on: ubuntu-latest
     steps:
@@ -84,7 +124,20 @@ jobs:
 
       - name: Start containers
         run: docker-compose -f cit-api/docker-compose.yml up --build cit-api-pipeline
-
+        
+        # docker-compose will return 0 even if python container returns non-zero or crashes
+        # ensure job fails if python container returns non-zero code or crashes
+      - name: check Container Status
+        run: | 
+          container_status=$(docker ps --filter 'status=exited' --format '{{.Status}}')
+          if [[ $container_status == *"Exited (0)"* ]]; 
+          then 
+            echo "Container exited successfully"
+          else 
+            echo "Container exited with error: $container_status"
+            exit 1
+          fi                
+          
   run-housing:
     runs-on: ubuntu-latest
     steps:
@@ -103,7 +156,20 @@ jobs:
 
       - name: Start containers
         run: docker-compose -f cit-api/docker-compose.yml up --build cit-api-pipeline
-  
+          
+        # docker-compose will return 0 even if python container returns non-zero or crashes
+        # ensure job fails if python container returns non-zero code or crashes
+      - name: check Container Status
+        run: | 
+          container_status=$(docker ps --filter 'status=exited' --format '{{.Status}}')
+          if [[ $container_status == *"Exited (0)"* ]]; 
+          then 
+            echo "Container exited successfully"
+          else 
+            echo "Container exited with error: $container_status"
+            exit 1
+          fi                
+          
   run-municipal-tax-rates:
     runs-on: ubuntu-latest
     steps:
@@ -122,7 +188,20 @@ jobs:
 
       - name: Start containers
         run: docker-compose -f cit-api/docker-compose.yml up --build cit-api-pipeline
-
+        
+        # docker-compose will return 0 even if python container returns non-zero or crashes
+        # ensure job fails if python container returns non-zero code or crashes
+      - name: check Container Status
+        run: | 
+          container_status=$(docker ps --filter 'status=exited' --format '{{.Status}}')
+          if [[ $container_status == *"Exited (0)"* ]]; 
+          then 
+            echo "Container exited successfully"
+          else 
+            echo "Container exited with error: $container_status"
+            exit 1
+          fi                
+          
   run-municipalities:
     runs-on: ubuntu-latest
     steps:
@@ -141,7 +220,20 @@ jobs:
 
       - name: Start containers
         run: docker-compose -f cit-api/docker-compose.yml up --build cit-api-pipeline
-
+        
+        # docker-compose will return 0 even if python container returns non-zero or crashes
+        # ensure job fails if python container returns non-zero code or crashes
+      - name: check Container Status
+        run: | 
+          container_status=$(docker ps --filter 'status=exited' --format '{{.Status}}')
+          if [[ $container_status == *"Exited (0)"* ]]; 
+          then 
+            echo "Container exited successfully"
+          else 
+            echo "Container exited with error: $container_status"
+            exit 1
+          fi                
+          
   run-nbd-phh-speeds:
     runs-on: ubuntu-latest
     steps:
@@ -160,7 +252,20 @@ jobs:
 
       - name: Start containers
         run: docker-compose -f cit-api/docker-compose.yml up --build cit-api-pipeline
-
+        
+        # docker-compose will return 0 even if python container returns non-zero or crashes
+        # ensure job fails if python container returns non-zero code or crashes
+      - name: check Container Status
+        run: | 
+          container_status=$(docker ps --filter 'status=exited' --format '{{.Status}}')
+          if [[ $container_status == *"Exited (0)"* ]]; 
+          then 
+            echo "Container exited successfully"
+          else 
+            echo "Container exited with error: $container_status"
+            exit 1
+          fi                
+          
   run-phdeomographic:
     runs-on: ubuntu-latest
     steps:
@@ -179,7 +284,20 @@ jobs:
 
       - name: Start containers
         run: docker-compose -f cit-api/docker-compose.yml up --build cit-api-pipeline
-  
+          
+        # docker-compose will return 0 even if python container returns non-zero or crashes
+        # ensure job fails if python container returns non-zero code or crashes
+      - name: check Container Status
+        run: | 
+          container_status=$(docker ps --filter 'status=exited' --format '{{.Status}}')
+          if [[ $container_status == *"Exited (0)"* ]]; 
+          then 
+            echo "Container exited successfully"
+          else 
+            echo "Container exited with error: $container_status"
+            exit 1
+          fi                
+          
   run-regional-districts:
     runs-on: ubuntu-latest
     steps:
@@ -198,7 +316,20 @@ jobs:
 
       - name: Start containers
         run: docker-compose -f cit-api/docker-compose.yml up --build cit-api-pipeline
-
+        
+        # docker-compose will return 0 even if python container returns non-zero or crashes
+        # ensure job fails if python container returns non-zero code or crashes
+      - name: check Container Status
+        run: | 
+          container_status=$(docker ps --filter 'status=exited' --format '{{.Status}}')
+          if [[ $container_status == *"Exited (0)"* ]]; 
+          then 
+            echo "Container exited successfully"
+          else 
+            echo "Container exited with error: $container_status"
+            exit 1
+          fi                
+          
   run-school-districts:
     runs-on: ubuntu-latest
     steps:
@@ -217,7 +348,20 @@ jobs:
 
       - name: Start containers
         run: docker-compose -f cit-api/docker-compose.yml up --build cit-api-pipeline
-
+        
+        # docker-compose will return 0 even if python container returns non-zero or crashes
+        # ensure job fails if python container returns non-zero code or crashes
+      - name: check Container Status
+        run: | 
+          container_status=$(docker ps --filter 'status=exited' --format '{{.Status}}')
+          if [[ $container_status == *"Exited (0)"* ]]; 
+          then 
+            echo "Container exited successfully"
+          else 
+            echo "Container exited with error: $container_status"
+            exit 1
+          fi                
+          
   run-tourism-region:
     runs-on: ubuntu-latest
     steps:
@@ -236,7 +380,20 @@ jobs:
 
       - name: Start containers
         run: docker-compose -f cit-api/docker-compose.yml up --build cit-api-pipeline
-  
+          
+        # docker-compose will return 0 even if python container returns non-zero or crashes
+        # ensure job fails if python container returns non-zero code or crashes
+      - name: check Container Status
+        run: | 
+          container_status=$(docker ps --filter 'status=exited' --format '{{.Status}}')
+          if [[ $container_status == *"Exited (0)"* ]]; 
+          then 
+            echo "Container exited successfully"
+          else 
+            echo "Container exited with error: $container_status"
+            exit 1
+          fi                
+          
   run-tsunami-zones:
     runs-on: ubuntu-latest
     steps:
@@ -255,7 +412,20 @@ jobs:
 
       - name: Start containers
         run: docker-compose -f cit-api/docker-compose.yml up --build cit-api-pipeline
-
+        
+        # docker-compose will return 0 even if python container returns non-zero or crashes
+        # ensure job fails if python container returns non-zero code or crashes
+      - name: check Container Status
+        run: | 
+          container_status=$(docker ps --filter 'status=exited' --format '{{.Status}}')
+          if [[ $container_status == *"Exited (0)"* ]]; 
+          then 
+            echo "Container exited successfully"
+          else 
+            echo "Container exited with error: $container_status"
+            exit 1
+          fi                
+          
   run-wildfire-zones:
     runs-on: ubuntu-latest
     steps:
@@ -274,3 +444,17 @@ jobs:
 
       - name: Start containers
         run: docker-compose -f cit-api/docker-compose.yml up --build cit-api-pipeline
+                
+        # docker-compose will return 0 even if python container returns non-zero or crashes
+        # ensure job fails if python container returns non-zero code or crashes
+      - name: check Container Status
+        run: | 
+          container_status=$(docker ps --filter 'status=exited' --format '{{.Status}}')
+          if [[ $container_status == *"Exited (0)"* ]]; 
+          then 
+            echo "Container exited successfully"
+          else 
+            echo "Container exited with error: $container_status"
+            exit 1
+          fi                
+        
diff --git a/.github/workflows/pipeline-bucket4-semiannually.yml b/.github/workflows/pipeline-bucket4-semiannually.yml
--- a/.github/workflows/pipeline-bucket4-semiannually.yml
+++ b/.github/workflows/pipeline-bucket4-semiannually.yml
@@ -31,7 +31,20 @@ jobs:
 
       - name: Start containers
         run: docker-compose -f cit-api/docker-compose.yml up --build cit-api-pipeline
-
+      
+      # docker-compose will return 0 even if python container returns non-zero or crashes
+      # ensure job fails if python container returns non-zero code or crashes
+      - name: check Container Status
+        run: | 
+          container_status=$(docker ps --filter 'status=exited' --format '{{.Status}}')
+          if [[ $container_status == *"Exited (0)"* ]]; 
+          then 
+            echo "Container exited successfully"
+          else 
+            echo "Container exited with error: $container_status"
+            exit 1
+          fi
+        
   run-prod:
     runs-on: ubuntu-latest
     steps:
@@ -50,3 +63,17 @@ jobs:
 
       - name: Start containers
         run: docker-compose -f cit-api/docker-compose.yml up --build cit-api-pipeline
+                
+      # docker-compose will return 0 even if python container returns non-zero or crashes
+      # ensure job fails if python container returns non-zero code or crashes
+      - name: check Container Status
+        run: | 
+          container_status=$(docker ps --filter 'status=exited' --format '{{.Status}}')
+          if [[ $container_status == *"Exited (0)"* ]]; 
+          then 
+            echo "Container exited successfully"
+          else 
+            echo "Container exited with error: $container_status"
+            exit 1
+          fi
+        
